name: hsas_h4o5f_app
description: A smart community application developed by the H4o5F team from the High School Affiliated to SUSTech.
version: 1.2.5+37

environment:
  sdk: '>=3.0.0'
  flutter: '>=3.13.1'

dependencies:
  args: ^2.4.0
  built_collection: ^5.1.1
  built_value: ^8.6.1
  dynamic_color: ^1.6.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ">=10.0.0 <13.0.0"
  http: ^0.13.5
  intl: ^0.18.1
  parse_server_sdk_flutter: ">=6.0.0 <8.0.0"
  shared_preferences: ^2.0.18
  sliver_tools: ^0.2.10
  url_launcher: ^6.1.10
  flutter_svg: ^2.0.0
  vector_graphics: ^1.1.7
  package_info_plus: ^4.0.2
  camera: ^0.10.5+3
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  built_value_generator: ^8.6.1
  build_runner: ^2.4.5

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/vectors/
