name: hsas_h4o5f_app
description: A smart community application developed by the H4o5F team from the High School Affiliated to SUSTech.
version: 1.0.2+1

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: '>=3.10.0'

dependencies:
  args: ^2.4.0
  dynamic_color: ^1.6.2
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.6
  flutter_localizations:
    sdk: flutter
  flutter_redux: ^0.10.0
  go_router: ^8.0.1
  http: ^0.13.5
  intl: any
  parse_server_sdk_flutter: ^5.0.0
  redux: ^5.0.0
  shared_preferences: ^2.0.18
  sliver_tools: ^0.2.10
  tuple: ^2.0.1
  url_launcher: ^6.1.10
  xml: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true